version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: web # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forwarding

  express: # name of the second service
    build: api # specify the directory of the Dockerfile
    ports:
      - "3000:3000"
    links:
      - database # link this service to the database service
  
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
